### ISSUE TITLE
Neaktualne wsdl

### ISSUE THREAD

**Issue by PayteR** [tomaj/omnipay-tatra#10]
Zdravim, chcel som implementovat tuto package, no z Tatrabanky mi povedali, ze obsahuje neaktualne wsdl https://github.com/tomaj/omnipay-tatra/blob/master/src/ComfortPay/comfortpay.wsdl, viete mi povedat, kedy a ci bude update? vdaka

**Comment by tomaj** [comment]
je to v procese - tu je pull request - https://github.com/tomaj/omnipay-tatra/pull/9
po jeho mergnuti by to malo byt v poriadku

**Comment by PayteR** [comment]
Kedy zhruba sa da ocakavat merge?

**Comment by tomaj** [comment]
je to uz releasnute
